#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Tgf_SwordMaster_RuneSword_SkillHelper

#include "Basic.hpp"

#include "ABP_Tgf_SwordMaster_RuneSword_SkillHelper_classes.hpp"
#include "ABP_Tgf_SwordMaster_RuneSword_SkillHelper_parameters.hpp"


namespace SDK
{

// Function ABP_Tgf_SwordMaster_RuneSword_SkillHelper.ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_Tgf_SwordMaster_RuneSword_SkillHelper_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C", "AnimGraph");

	Params::ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_Tgf_SwordMaster_RuneSword_SkillHelper.ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C.BlueprintThreadSafeUpdateAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Tgf_SwordMaster_RuneSword_SkillHelper_C::BlueprintThreadSafeUpdateAnimation(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C", "BlueprintThreadSafeUpdateAnimation");

	Params::ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C_BlueprintThreadSafeUpdateAnimation Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Tgf_SwordMaster_RuneSword_SkillHelper.ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C.ExecuteUbergraph_ABP_Tgf_SwordMaster_RuneSword_SkillHelper
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Tgf_SwordMaster_RuneSword_SkillHelper_C::ExecuteUbergraph_ABP_Tgf_SwordMaster_RuneSword_SkillHelper(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C", "ExecuteUbergraph_ABP_Tgf_SwordMaster_RuneSword_SkillHelper");

	Params::ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C_ExecuteUbergraph_ABP_Tgf_SwordMaster_RuneSword_SkillHelper Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Tgf_SwordMaster_RuneSword_SkillHelper.ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C.GetParentActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_Tgf_RuneSwordSkillHelperActor_C*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ABP_Tgf_RuneSwordSkillHelperActor_C* UABP_Tgf_SwordMaster_RuneSword_SkillHelper_C::GetParentActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C", "GetParentActor");

	Params::ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C_GetParentActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_Tgf_SwordMaster_RuneSword_SkillHelper.ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C.SelectAimingAnimation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FAnimUpdateContext               Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FAnimNodeReference               Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UABP_Tgf_SwordMaster_RuneSword_SkillHelper_C::SelectAimingAnimation(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C", "SelectAimingAnimation");

	Params::ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C_SelectAimingAnimation Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Tgf_SwordMaster_RuneSword_SkillHelper.ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C.UpdateAimingData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Tgf_SwordMaster_RuneSword_SkillHelper_C::UpdateAimingData(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C", "UpdateAimingData");

	Params::ABP_Tgf_SwordMaster_RuneSword_SkillHelper_C_UpdateAimingData Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

