#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_TGF_Soul

#include "Basic.hpp"

#include "B_TGF_Soul_classes.hpp"
#include "B_TGF_Soul_parameters.hpp"


namespace SDK
{

// Function B_TGF_Soul.B_TGF_Soul_C.ApplyEffect
// (BlueprintCallable, BlueprintEvent)

void AB_TGF_Soul_C::ApplyEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "ApplyEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_TGF_Soul.B_TGF_Soul_C.DoExceedMaxTime
// (BlueprintCallable, BlueprintEvent)

void AB_TGF_Soul_C::DoExceedMaxTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "DoExceedMaxTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_TGF_Soul.B_TGF_Soul_C.DoSearch
// (BlueprintCallable, BlueprintEvent)

void AB_TGF_Soul_C::DoSearch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "DoSearch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_TGF_Soul.B_TGF_Soul_C.ExecuteUbergraph_B_TGF_Soul
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_TGF_Soul_C::ExecuteUbergraph_B_TGF_Soul(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "ExecuteUbergraph_B_TGF_Soul");

	Params::B_TGF_Soul_C_ExecuteUbergraph_B_TGF_Soul Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_TGF_Soul.B_TGF_Soul_C.MoveToTarget
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AB_TGF_Soul_C::MoveToTarget(class AActor* TargetActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "MoveToTarget");

	Params::B_TGF_Soul_C_MoveToTarget Parms{};

	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_TGF_Soul.B_TGF_Soul_C.PlayHitFx
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AB_TGF_Soul_C::PlayHitFx()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "PlayHitFx");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_TGF_Soul.B_TGF_Soul_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_TGF_Soul_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_TGF_Soul.B_TGF_Soul_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_TGF_Soul_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "ReceiveTick");

	Params::B_TGF_Soul_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_TGF_Soul.B_TGF_Soul_C.RefreshVelocity
// (BlueprintCallable, BlueprintEvent)

void AB_TGF_Soul_C::RefreshVelocity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_TGF_Soul_C", "RefreshVelocity");

	UObject::ProcessEvent(Func, nullptr);
}

}

