#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_TGF_WeaponInstance_Base

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "LyraGame_structs.hpp"


namespace SDK::Params
{

// Function B_TGF_WeaponInstance_Base.B_TGF_WeaponInstance_Base_C.DetermineCosmeticTags
// 0x0088 (0x0088 - 0x0000)
struct B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags final
{
public:
	class ULyraPawnComponent_CharacterParts*      CosmeticComponent;                                 // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetSpawnedActors_ReturnValue;             // 0x0018(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AB_TGF_MeleeWeaponBase_C*               K2Node_DynamicCast_AsB_TGF_Melee_Weapon_Base;      // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_GetCombinedTags_ReturnValue;              // 0x0050(0x0020)()
	class APawn*                                  CallFunc_GetPawn_ReturnValue;                      // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULyraPawnComponent_CharacterParts*      CallFunc_GetComponentByClass_ReturnValue;          // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags) == 0x000008, "Wrong alignment on B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags");
static_assert(sizeof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags) == 0x000088, "Wrong size on B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CosmeticComponent) == 0x000000, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CosmeticComponent' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, Temp_int_Array_Index_Variable) == 0x000008, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_GetSpawnedActors_ReturnValue) == 0x000018, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_GetSpawnedActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_Array_Get_Item) == 0x000030, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, K2Node_DynamicCast_AsB_TGF_Melee_Weapon_Base) == 0x000038, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::K2Node_DynamicCast_AsB_TGF_Melee_Weapon_Base' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_Array_Length_ReturnValue) == 0x000044, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_Less_IntInt_ReturnValue) == 0x000048, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_GetCombinedTags_ReturnValue) == 0x000050, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_GetCombinedTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_GetPawn_ReturnValue) == 0x000070, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_GetComponentByClass_ReturnValue) == 0x000078, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags, CallFunc_IsValid_ReturnValue_1) == 0x000080, "Member 'B_TGF_WeaponInstance_Base_C_DetermineCosmeticTags::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function B_TGF_WeaponInstance_Base.B_TGF_WeaponInstance_Base_C.ExecuteUbergraph_B_TGF_WeaponInstance_Base
// 0x0030 (0x0030 - 0x0000)
struct B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeGameplayTagContainerFromTag_ReturnValue; // 0x0008(0x0020)()
	int32                                         CallFunc_RemoveGameplayEffectWithSourceObjectAndTags_ReturnValue; // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base) == 0x000008, "Wrong alignment on B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base");
static_assert(sizeof(B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base) == 0x000030, "Wrong size on B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base, EntryPoint) == 0x000000, "Member 'B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base, CallFunc_MakeGameplayTagContainerFromTag_ReturnValue) == 0x000008, "Member 'B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base::CallFunc_MakeGameplayTagContainerFromTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base, CallFunc_RemoveGameplayEffectWithSourceObjectAndTags_ReturnValue) == 0x000028, "Member 'B_TGF_WeaponInstance_Base_C_ExecuteUbergraph_B_TGF_WeaponInstance_Base::CallFunc_RemoveGameplayEffectWithSourceObjectAndTags_ReturnValue' has a wrong offset!");

// Function B_TGF_WeaponInstance_Base.B_TGF_WeaponInstance_Base_C.InitMaterials
// 0x0240 (0x0240 - 0x0000)
struct B_TGF_WeaponInstance_Base_C_InitMaterials final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetSpawnedActors_ReturnValue;             // 0x0028(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetPawn_ReturnValue;                      // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTgfActorCustomDepthStencilManagerComponent* CallFunc_GetComponentByClass_ReturnValue;          // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetCurrentStencilValue_ReturnValue;       // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_6;                   // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_6;                  // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_7;                  // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_7;                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_8;                  // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_7;                   // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_8;                 // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_8;                   // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AB_WeaponBase_C*                        K2Node_DynamicCast_AsB_Weapon_Base;                // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x3];                                       // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_9;                   // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_9;                  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_9;                 // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetConsoleVariableBoolValue_ReturnValue;  // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetConsoleVariableBoolValue_ReturnValue_1; // 0x00CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CE[0x2];                                       // 0x00CE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetSpawnedActors_ReturnValue_1;           // 0x00D0(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_Array_Get_Item_2;                         // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_WeaponBase_C*                        K2Node_DynamicCast_AsB_Weapon_Base_1;              // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UNiagaraComponent*>              CallFunc_K2_GetComponentsByClass_ReturnValue;      // 0x0108(0x0010)(ReferenceParm, ContainsInstancedReference)
	class ULocalLightComponent*                   CallFunc_GetComponentByClass_ReturnValue_1;        // 0x0118(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0125(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_126[0x2];                                      // 0x0126(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_3;                         // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_Array_Get_Item_4;                         // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AB_WeaponBase_C*                        K2Node_DynamicCast_AsB_Weapon_Base_2;              // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_WeaponBase_C*                        K2Node_DynamicCast_AsB_Weapon_Base_3;              // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMeshComponent*>                 CallFunc_K2_GetComponentsByClass_ReturnValue_1;    // 0x0158(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UMeshComponent*>                 CallFunc_K2_GetComponentsByClass_ReturnValue_2;    // 0x0168(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UMeshComponent*                         CallFunc_Array_Get_Item_5;                         // 0x0178(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_Array_Get_Item_6;                         // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_192[0x2];                                      // 0x0192(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x019C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x019D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19E[0x2];                                      // 0x019E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_7;               // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETgfStencilRef                                CallFunc_GetStencilDef_ReturnValue;                // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x01A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1AA[0x2];                                      // 0x01AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_10;                 // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_7;                // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B1[0x3];                                      // 0x01B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_10;                // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_10;                  // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasTag_ReturnValue;                       // 0x01BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BD[0x3];                                      // 0x01BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_Array_Get_Item_7;                         // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_GetSpawnedActors_ReturnValue_2;           // 0x01C8(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_8;               // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1DC[0x4];                                      // 0x01DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_8;                         // 0x01E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_8;                // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UNiagaraComponent*>              CallFunc_K2_GetComponentsByClass_ReturnValue_3;    // 0x01F0(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UNiagaraComponent*                      CallFunc_Array_Get_Item_9;                         // 0x0200(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_9;               // 0x0208(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_9;                // 0x020C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20D[0x3];                                      // 0x020D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMeshComponent*>                 CallFunc_K2_GetComponentsByClass_ReturnValue_4;    // 0x0210(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UMeshComponent*                         CallFunc_Array_Get_Item_10;                        // 0x0220(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_10;              // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_10;               // 0x022C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22D[0x3];                                      // 0x022D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_WeaponBase_C*                        K2Node_DynamicCast_AsB_Weapon_Base_4;              // 0x0230(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_TGF_WeaponInstance_Base_C_InitMaterials) == 0x000008, "Wrong alignment on B_TGF_WeaponInstance_Base_C_InitMaterials");
static_assert(sizeof(B_TGF_WeaponInstance_Base_C_InitMaterials) == 0x000240, "Wrong size on B_TGF_WeaponInstance_Base_C_InitMaterials");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue) == 0x000004, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable) == 0x000008, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_1) == 0x00000C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_1) == 0x000010, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_1) == 0x000014, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_2) == 0x000018, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_2) == 0x00001C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_2) == 0x000020, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetSpawnedActors_ReturnValue) == 0x000028, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetSpawnedActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_3) == 0x00003C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetPawn_ReturnValue) == 0x000040, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_IsValid_ReturnValue) == 0x000048, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetComponentByClass_ReturnValue) == 0x000050, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_IsValid_ReturnValue_1) == 0x000058, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetCurrentStencilValue_ReturnValue) == 0x00005C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetCurrentStencilValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_3) == 0x000060, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_4) == 0x000064, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_3) == 0x000068, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_4) == 0x00006C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_4) == 0x000070, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_5) == 0x000074, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_5) == 0x000078, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_5) == 0x00007C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_6) == 0x000080, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_6' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_6) == 0x000084, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_6' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_7) == 0x000088, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_7' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_6) == 0x00008C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_7) == 0x000090, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_8) == 0x000094, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_8' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_7) == 0x000098, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_7' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_8) == 0x00009C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_8) == 0x0000A0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_8' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item) == 0x0000A8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_AsB_Weapon_Base) == 0x0000B0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_AsB_Weapon_Base' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_bSuccess) == 0x0000B8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_9) == 0x0000BC, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_9' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_9) == 0x0000C0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_9' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue) == 0x0000C4, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_9) == 0x0000C8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetConsoleVariableBoolValue_ReturnValue) == 0x0000CC, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetConsoleVariableBoolValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetConsoleVariableBoolValue_ReturnValue_1) == 0x0000CD, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetConsoleVariableBoolValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetSpawnedActors_ReturnValue_1) == 0x0000D0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetSpawnedActors_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_1) == 0x0000E0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_2) == 0x0000E8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_IsValid_ReturnValue_2) == 0x0000F0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_AsB_Weapon_Base_1) == 0x0000F8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_AsB_Weapon_Base_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_bSuccess_1) == 0x000100, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_K2_GetComponentsByClass_ReturnValue) == 0x000108, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_K2_GetComponentsByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetComponentByClass_ReturnValue_1) == 0x000118, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetComponentByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_1) == 0x000120, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_IsValid_ReturnValue_3) == 0x000124, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_1) == 0x000125, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_3) == 0x000128, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_4) == 0x000130, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_AsB_Weapon_Base_2) == 0x000138, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_AsB_Weapon_Base_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_bSuccess_2) == 0x000140, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_AsB_Weapon_Base_3) == 0x000148, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_AsB_Weapon_Base_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_bSuccess_3) == 0x000150, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_K2_GetComponentsByClass_ReturnValue_1) == 0x000158, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_K2_GetComponentsByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_K2_GetComponentsByClass_ReturnValue_2) == 0x000168, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_K2_GetComponentsByClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_5) == 0x000178, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_6) == 0x000180, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_2) == 0x000188, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_3) == 0x00018C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_2) == 0x000190, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_3) == 0x000191, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_4) == 0x000194, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_5) == 0x000198, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_4) == 0x00019C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_5) == 0x00019D, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_6) == 0x0001A0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_7) == 0x0001A4, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetStencilDef_ReturnValue) == 0x0001A8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetStencilDef_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_6) == 0x0001A9, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Loop_Counter_Variable_10) == 0x0001AC, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Loop_Counter_Variable_10' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_7) == 0x0001B0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Add_IntInt_ReturnValue_10) == 0x0001B4, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Add_IntInt_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, Temp_int_Array_Index_Variable_10) == 0x0001B8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::Temp_int_Array_Index_Variable_10' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_HasTag_ReturnValue) == 0x0001BC, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_HasTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_7) == 0x0001C0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_7' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_GetSpawnedActors_ReturnValue_2) == 0x0001C8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_GetSpawnedActors_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_8) == 0x0001D8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_8) == 0x0001E0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_8' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_8) == 0x0001E8, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_K2_GetComponentsByClass_ReturnValue_3) == 0x0001F0, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_K2_GetComponentsByClass_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_9) == 0x000200, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_9' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_9) == 0x000208, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_9) == 0x00020C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_K2_GetComponentsByClass_ReturnValue_4) == 0x000210, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_K2_GetComponentsByClass_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Get_Item_10) == 0x000220, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Get_Item_10' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Array_Length_ReturnValue_10) == 0x000228, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Array_Length_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, CallFunc_Less_IntInt_ReturnValue_10) == 0x00022C, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::CallFunc_Less_IntInt_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_AsB_Weapon_Base_4) == 0x000230, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_AsB_Weapon_Base_4' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_InitMaterials, K2Node_DynamicCast_bSuccess_4) == 0x000238, "Member 'B_TGF_WeaponInstance_Base_C_InitMaterials::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");

// Function B_TGF_WeaponInstance_Base.B_TGF_WeaponInstance_Base_C.SetCosmeticTags
// 0x0068 (0x0068 - 0x0000)
struct B_TGF_WeaponInstance_Base_C_SetCosmeticTags final
{
public:
	struct FGameplayTagContainer                  CosmeticTag;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetSpawnedActors_ReturnValue;             // 0x0030(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_TGF_MeleeWeaponBase_C*               K2Node_DynamicCast_AsB_TGF_Melee_Weapon_Base;      // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags) == 0x000008, "Wrong alignment on B_TGF_WeaponInstance_Base_C_SetCosmeticTags");
static_assert(sizeof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags) == 0x000068, "Wrong size on B_TGF_WeaponInstance_Base_C_SetCosmeticTags");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, CosmeticTag) == 0x000000, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::CosmeticTag' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, Temp_int_Array_Index_Variable) == 0x000020, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, CallFunc_GetSpawnedActors_ReturnValue) == 0x000030, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::CallFunc_GetSpawnedActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, CallFunc_Array_Get_Item) == 0x000048, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, CallFunc_Less_IntInt_ReturnValue) == 0x000050, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, K2Node_DynamicCast_AsB_TGF_Melee_Weapon_Base) == 0x000058, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::K2Node_DynamicCast_AsB_TGF_Melee_Weapon_Base' has a wrong offset!");
static_assert(offsetof(B_TGF_WeaponInstance_Base_C_SetCosmeticTags, K2Node_DynamicCast_bSuccess) == 0x000060, "Member 'B_TGF_WeaponInstance_Base_C_SetCosmeticTags::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

