#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_TgfUIFunctions

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"
#include "LyraGame_structs.hpp"


namespace SDK::Params
{

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.Discard Item From Equipment
// 0x0028 (0x0028 - 0x0000)
struct BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment final
{
public:
	class UTgfEquipmentWrapper*                   Equipment;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTgfInventoryWrapper*                   InventoryContext;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ALyraCharacter*                         OwningCharacter;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         StackCount;                                        // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment");
static_assert(sizeof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment) == 0x000028, "Wrong size on BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment, Equipment) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment::Equipment' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment, InventoryContext) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment::InventoryContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment, OwningCharacter) == 0x000010, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment::OwningCharacter' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment, __WorldContext) == 0x000018, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment, StackCount) == 0x000020, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_From_Equipment::StackCount' has a wrong offset!");

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.Discard Item from Inventory
// 0x0020 (0x0020 - 0x0000)
struct BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory final
{
public:
	class UTgfInventoryItemWrapper*               Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTgfInventoryWrapper*                   InventoryContext;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ALyraCharacter*                         OwningCharacter;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory");
static_assert(sizeof(BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory) == 0x000020, "Wrong size on BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory, Item) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory::Item' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory, InventoryContext) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory::InventoryContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory, OwningCharacter) == 0x000010, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory::OwningCharacter' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory, __WorldContext) == 0x000018, "Member 'BPFL_TgfUIFunctions_C_Discard_Item_from_Inventory::__WorldContext' has a wrong offset!");

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.GetEquipmentSlotIconScale
// 0x0150 (0x0150 - 0x0000)
struct BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale final
{
public:
	ETgfEquipSubType                              Type;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Scale;                                             // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETgfEquipSubType                              Temp_byte_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable;                                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1;                              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2;                              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3;                              // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_4;                              // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_5;                              // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_6;                              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_7;                              // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_8;                              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_9;                              // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_10;                             // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_11;                             // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_12;                             // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_13;                             // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_14;                             // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_15;                             // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_16;                             // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_17;                             // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_18;                             // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_19;                             // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_20;                             // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_21;                             // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_22;                             // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_23;                             // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_24;                             // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_25;                             // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_26;                             // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_27;                             // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_28;                             // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_29;                             // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_30;                             // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_31;                             // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_32;                             // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_33;                             // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_34;                             // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_35;                             // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_36;                             // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Select_Default;                             // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale");
static_assert(sizeof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale) == 0x000150, "Wrong size on BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Type) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Type' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, __WorldContext) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Scale) == 0x000010, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Scale' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_byte_Variable) == 0x000018, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable) == 0x000020, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_1) == 0x000028, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_2) == 0x000030, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_2' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_3) == 0x000038, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_3' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_4) == 0x000040, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_4' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_5) == 0x000048, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_5' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_6) == 0x000050, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_6' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_7) == 0x000058, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_7' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_8) == 0x000060, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_8' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_9) == 0x000068, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_9' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_10) == 0x000070, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_10' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_11) == 0x000078, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_11' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_12) == 0x000080, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_12' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_13) == 0x000088, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_13' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_14) == 0x000090, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_14' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_15) == 0x000098, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_15' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_16) == 0x0000A0, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_16' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_17) == 0x0000A8, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_17' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_18) == 0x0000B0, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_18' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_19) == 0x0000B8, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_19' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_20) == 0x0000C0, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_20' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_21) == 0x0000C8, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_21' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_22) == 0x0000D0, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_22' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_23) == 0x0000D8, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_23' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_24) == 0x0000E0, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_24' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_25) == 0x0000E8, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_25' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_26) == 0x0000F0, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_26' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_27) == 0x0000F8, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_27' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_28) == 0x000100, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_28' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_29) == 0x000108, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_29' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_30) == 0x000110, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_30' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_31) == 0x000118, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_31' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_32) == 0x000120, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_32' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_33) == 0x000128, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_33' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_34) == 0x000130, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_34' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_35) == 0x000138, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_35' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, Temp_real_Variable_36) == 0x000140, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::Temp_real_Variable_36' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale, K2Node_Select_Default) == 0x000148, "Member 'BPFL_TgfUIFunctions_C_GetEquipmentSlotIconScale::K2Node_Select_Default' has a wrong offset!");

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.GetInputKey
// 0x0068 (0x0068 - 0x0000)
struct BPFL_TgfUIFunctions_C_GetInputKey final
{
public:
	struct FGameplayTag                           InputTag;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            OwnerWidget;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FKey                                   Key;                                               // 0x0018(0x0018)(Parm, OutParm, HasGetValueTypeHash)
	const class UInputAction*                     CallFunc_FindInputActionForTag_ReturnValue;        // 0x0030(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULocalPlayer*                           CallFunc_GetOwningLocalPlayer_ReturnValue;         // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULyraLocalPlayer*                       K2Node_DynamicCast_AsLyra_Local_Player;            // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   CallFunc_GetInputKeyByInputAction_ReturnValue;     // 0x0050(0x0018)(HasGetValueTypeHash)
};
static_assert(alignof(BPFL_TgfUIFunctions_C_GetInputKey) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_GetInputKey");
static_assert(sizeof(BPFL_TgfUIFunctions_C_GetInputKey) == 0x000068, "Wrong size on BPFL_TgfUIFunctions_C_GetInputKey");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, InputTag) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::InputTag' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, OwnerWidget) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::OwnerWidget' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, __WorldContext) == 0x000010, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, Key) == 0x000018, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::Key' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, CallFunc_FindInputActionForTag_ReturnValue) == 0x000030, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::CallFunc_FindInputActionForTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, CallFunc_GetOwningLocalPlayer_ReturnValue) == 0x000038, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::CallFunc_GetOwningLocalPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, K2Node_DynamicCast_AsLyra_Local_Player) == 0x000040, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::K2Node_DynamicCast_AsLyra_Local_Player' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetInputKey, CallFunc_GetInputKeyByInputAction_ReturnValue) == 0x000050, "Member 'BPFL_TgfUIFunctions_C_GetInputKey::CallFunc_GetInputKeyByInputAction_ReturnValue' has a wrong offset!");

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.GetKeyDisplayName
// 0x0068 (0x0068 - 0x0000)
struct BPFL_TgfUIFunctions_C_GetKeyDisplayName final
{
public:
	struct FGameplayTag                           InputTag;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            OwnerWidget;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   DisplayName;                                       // 0x0018(0x0018)(Parm, OutParm)
	const class UInputAction*                     CallFunc_FindInputActionForTag_ReturnValue;        // 0x0030(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULocalPlayer*                           CallFunc_GetOwningLocalPlayer_ReturnValue;         // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULyraLocalPlayer*                       K2Node_DynamicCast_AsLyra_Local_Player;            // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetInputKeyTextByInputAction_ReturnValue; // 0x0050(0x0018)()
};
static_assert(alignof(BPFL_TgfUIFunctions_C_GetKeyDisplayName) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_GetKeyDisplayName");
static_assert(sizeof(BPFL_TgfUIFunctions_C_GetKeyDisplayName) == 0x000068, "Wrong size on BPFL_TgfUIFunctions_C_GetKeyDisplayName");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, InputTag) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::InputTag' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, OwnerWidget) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::OwnerWidget' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, __WorldContext) == 0x000010, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, DisplayName) == 0x000018, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::DisplayName' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, CallFunc_FindInputActionForTag_ReturnValue) == 0x000030, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::CallFunc_FindInputActionForTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, CallFunc_GetOwningLocalPlayer_ReturnValue) == 0x000038, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::CallFunc_GetOwningLocalPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, K2Node_DynamicCast_AsLyra_Local_Player) == 0x000040, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::K2Node_DynamicCast_AsLyra_Local_Player' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_GetKeyDisplayName, CallFunc_GetInputKeyTextByInputAction_ReturnValue) == 0x000050, "Member 'BPFL_TgfUIFunctions_C_GetKeyDisplayName::CallFunc_GetInputKeyTextByInputAction_ReturnValue' has a wrong offset!");

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.SetInputBtnName
// 0x0050 (0x0050 - 0x0000)
struct BPFL_TgfUIFunctions_C_SetInputBtnName final
{
public:
	struct FGameplayTag                           InputTag;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class UWBP_KeyMap_Common_C*                   TargetWidget;                                      // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULocalPlayer*                           CallFunc_GetOwningLocalPlayer_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     CallFunc_FindInputActionForTag_ReturnValue;        // 0x0020(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULyraLocalPlayer*                       K2Node_DynamicCast_AsLyra_Local_Player;            // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetInputKeyTextByInputAction_ReturnValue; // 0x0038(0x0018)()
};
static_assert(alignof(BPFL_TgfUIFunctions_C_SetInputBtnName) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_SetInputBtnName");
static_assert(sizeof(BPFL_TgfUIFunctions_C_SetInputBtnName) == 0x000050, "Wrong size on BPFL_TgfUIFunctions_C_SetInputBtnName");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, InputTag) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::InputTag' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, TargetWidget) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::TargetWidget' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, __WorldContext) == 0x000010, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, CallFunc_GetOwningLocalPlayer_ReturnValue) == 0x000018, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::CallFunc_GetOwningLocalPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, CallFunc_FindInputActionForTag_ReturnValue) == 0x000020, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::CallFunc_FindInputActionForTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, K2Node_DynamicCast_AsLyra_Local_Player) == 0x000028, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::K2Node_DynamicCast_AsLyra_Local_Player' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetInputBtnName, CallFunc_GetInputKeyTextByInputAction_ReturnValue) == 0x000038, "Member 'BPFL_TgfUIFunctions_C_SetInputBtnName::CallFunc_GetInputKeyTextByInputAction_ReturnValue' has a wrong offset!");

// Function BPFL_TgfUIFunctions.BPFL_TgfUIFunctions_C.SetRichText
// 0x00B8 (0x00B8 - 0x0000)
struct BPFL_TgfUIFunctions_C_SetRichText final
{
public:
	class URichTextBlock*                         Label;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   InText;                                            // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UObject*                                __WorldContext;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0028(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0088(0x0010)(ReferenceParm)
	bool                                          CallFunc_EndsWith_ReturnValue;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A0(0x0018)()
};
static_assert(alignof(BPFL_TgfUIFunctions_C_SetRichText) == 0x000008, "Wrong alignment on BPFL_TgfUIFunctions_C_SetRichText");
static_assert(sizeof(BPFL_TgfUIFunctions_C_SetRichText) == 0x0000B8, "Wrong size on BPFL_TgfUIFunctions_C_SetRichText");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, Label) == 0x000000, "Member 'BPFL_TgfUIFunctions_C_SetRichText::Label' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, InText) == 0x000008, "Member 'BPFL_TgfUIFunctions_C_SetRichText::InText' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, __WorldContext) == 0x000020, "Member 'BPFL_TgfUIFunctions_C_SetRichText::__WorldContext' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, K2Node_MakeStruct_FormatArgumentData) == 0x000028, "Member 'BPFL_TgfUIFunctions_C_SetRichText::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, CallFunc_Conv_TextToString_ReturnValue) == 0x000078, "Member 'BPFL_TgfUIFunctions_C_SetRichText::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, K2Node_MakeArray_Array) == 0x000088, "Member 'BPFL_TgfUIFunctions_C_SetRichText::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, CallFunc_EndsWith_ReturnValue) == 0x000098, "Member 'BPFL_TgfUIFunctions_C_SetRichText::CallFunc_EndsWith_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPFL_TgfUIFunctions_C_SetRichText, CallFunc_Format_ReturnValue) == 0x0000A0, "Member 'BPFL_TgfUIFunctions_C_SetRichText::CallFunc_Format_ReturnValue' has a wrong offset!");

}

