#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTS_TurnSlowly

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTS_TurnSlowly.BTS_TurnSlowly_C
// 0x0008 (0x00A0 - 0x0098)
class UBTS_TurnSlowly_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BTS_TurnSlowly(int32 EntryPoint);
	void ReceiveActivationAI(class AAIController* OwnerController, class APawn* ControlledPawn);
	void ReceiveDeactivationAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTS_TurnSlowly_C">();
	}
	static class UBTS_TurnSlowly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTS_TurnSlowly_C>();
	}
};
static_assert(alignof(UBTS_TurnSlowly_C) == 0x000008, "Wrong alignment on UBTS_TurnSlowly_C");
static_assert(sizeof(UBTS_TurnSlowly_C) == 0x0000A0, "Wrong size on UBTS_TurnSlowly_C");
static_assert(offsetof(UBTS_TurnSlowly_C, UberGraphFrame) == 0x000098, "Member 'UBTS_TurnSlowly_C::UberGraphFrame' has a wrong offset!");

}

