#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_SetWanderOnce

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTT_SetWanderOnce.BTT_SetWanderOnce_C
// 0x0030 (0x00D8 - 0x00A8)
class UBTT_SetWanderOnce_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 WanderOnce;                                        // 0x00B0(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BTT_SetWanderOnce(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTT_SetWanderOnce_C">();
	}
	static class UBTT_SetWanderOnce_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_SetWanderOnce_C>();
	}
};
static_assert(alignof(UBTT_SetWanderOnce_C) == 0x000008, "Wrong alignment on UBTT_SetWanderOnce_C");
static_assert(sizeof(UBTT_SetWanderOnce_C) == 0x0000D8, "Wrong size on UBTT_SetWanderOnce_C");
static_assert(offsetof(UBTT_SetWanderOnce_C, UberGraphFrame) == 0x0000A8, "Member 'UBTT_SetWanderOnce_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBTT_SetWanderOnce_C, WanderOnce) == 0x0000B0, "Member 'UBTT_SetWanderOnce_C::WanderOnce' has a wrong offset!");

}

