#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EMonsterDormantable

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EMonsterDormantable.EMonsterDormantable
// NumValues: 0x0004
enum class EMonsterDormantable : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EMonsterDormantable_MAX                  = 3,
};

}

