#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_TGF_OverviewMap

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_TGF_WidgetPage_classes.hpp"
#include "LyraGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_TGF_OverviewMap.GA_TGF_OverviewMap_C
// 0x0010 (0x06E8 - 0x06D8)
class UGA_TGF_OverviewMap_C final : public UGA_TGF_WidgetPage_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_TGF_OverviewMap_C;               // 0x06D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UItemFunctionLibrary*                   ItemFunctionLibrary;                               // 0x06E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_TGF_OverviewMap(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnWidgetPushSuccess(class UUserWidget* UserWidgetPage);

	bool K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_TGF_OverviewMap_C">();
	}
	static class UGA_TGF_OverviewMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_TGF_OverviewMap_C>();
	}
};
static_assert(alignof(UGA_TGF_OverviewMap_C) == 0x000008, "Wrong alignment on UGA_TGF_OverviewMap_C");
static_assert(sizeof(UGA_TGF_OverviewMap_C) == 0x0006E8, "Wrong size on UGA_TGF_OverviewMap_C");
static_assert(offsetof(UGA_TGF_OverviewMap_C, UberGraphFrame_GA_TGF_OverviewMap_C) == 0x0006D8, "Member 'UGA_TGF_OverviewMap_C::UberGraphFrame_GA_TGF_OverviewMap_C' has a wrong offset!");
static_assert(offsetof(UGA_TGF_OverviewMap_C, ItemFunctionLibrary) == 0x0006E0, "Member 'UGA_TGF_OverviewMap_C::ItemFunctionLibrary' has a wrong offset!");

}

