#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_TGF_WeaponOperationTips

#include "Basic.hpp"

#include "GA_TGF_WeaponOperationTips_classes.hpp"
#include "GA_TGF_WeaponOperationTips_parameters.hpp"


namespace SDK
{

// Function GA_TGF_WeaponOperationTips.GA_TGF_WeaponOperationTips_C.ExecuteUbergraph_GA_TGF_WeaponOperationTips
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_TGF_WeaponOperationTips_C::ExecuteUbergraph_GA_TGF_WeaponOperationTips(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_WeaponOperationTips_C", "ExecuteUbergraph_GA_TGF_WeaponOperationTips");

	Params::GA_TGF_WeaponOperationTips_C_ExecuteUbergraph_GA_TGF_WeaponOperationTips Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_TGF_WeaponOperationTips.GA_TGF_WeaponOperationTips_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_TGF_WeaponOperationTips_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_WeaponOperationTips_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

