#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_TGF_Hook_Stun

#include "Basic.hpp"

#include "GA_TGF_NoMoveRotAbility_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_TGF_Hook_Stun.GA_TGF_Hook_Stun_C
// 0x0000 (0x0D00 - 0x0D00)
class UGA_TGF_Hook_Stun_C final : public UGA_TGF_NoMoveRotAbility_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_TGF_Hook_Stun_C">();
	}
	static class UGA_TGF_Hook_Stun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_TGF_Hook_Stun_C>();
	}
};
static_assert(alignof(UGA_TGF_Hook_Stun_C) == 0x000010, "Wrong alignment on UGA_TGF_Hook_Stun_C");
static_assert(sizeof(UGA_TGF_Hook_Stun_C) == 0x000D00, "Wrong size on UGA_TGF_Hook_Stun_C");

}

