#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_TGF_AboutToStealthAdvance

#include "Basic.hpp"

#include "GA_TGF_AboutToStealthAdvance_classes.hpp"
#include "GA_TGF_AboutToStealthAdvance_parameters.hpp"


namespace SDK
{

// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.DeInitServer
// (BlueprintCallable, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::DeInitServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "DeInitServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.EnterStealth
// (BlueprintCallable, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::EnterStealth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "EnterStealth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.EventReceived_8125D7364B761085852CDA9F0F2C1670
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_TGF_AboutToStealthAdvance_C::EventReceived_8125D7364B761085852CDA9F0F2C1670(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "EventReceived_8125D7364B761085852CDA9F0F2C1670");

	Params::GA_TGF_AboutToStealthAdvance_C_EventReceived_8125D7364B761085852CDA9F0F2C1670 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.EventReceived_DB0785F44DB4542CAAB40F8D89116B8C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_TGF_AboutToStealthAdvance_C::EventReceived_DB0785F44DB4542CAAB40F8D89116B8C(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "EventReceived_DB0785F44DB4542CAAB40F8D89116B8C");

	Params::GA_TGF_AboutToStealthAdvance_C_EventReceived_DB0785F44DB4542CAAB40F8D89116B8C Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.EventReceived_EE32CD074EDCCA65DF5578A916D06B19
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_TGF_AboutToStealthAdvance_C::EventReceived_EE32CD074EDCCA65DF5578A916D06B19(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "EventReceived_EE32CD074EDCCA65DF5578A916D06B19");

	Params::GA_TGF_AboutToStealthAdvance_C_EventReceived_EE32CD074EDCCA65DF5578A916D06B19 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.ExecuteUbergraph_GA_TGF_AboutToStealthAdvance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_TGF_AboutToStealthAdvance_C::ExecuteUbergraph_GA_TGF_AboutToStealthAdvance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "ExecuteUbergraph_GA_TGF_AboutToStealthAdvance");

	Params::GA_TGF_AboutToStealthAdvance_C_ExecuteUbergraph_GA_TGF_AboutToStealthAdvance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.InitServer
// (BlueprintCallable, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::InitServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "InitServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_TGF_AboutToStealthAdvance_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "K2_OnEndAbility");

	Params::GA_TGF_AboutToStealthAdvance_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.LeaveStealth
// (BlueprintCallable, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::LeaveStealth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "LeaveStealth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.ResetMonitor
// (BlueprintCallable, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::ResetMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "ResetMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_TGF_AboutToStealthAdvance.GA_TGF_AboutToStealthAdvance_C.TellClientForceReset
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void UGA_TGF_AboutToStealthAdvance_C::TellClientForceReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_AboutToStealthAdvance_C", "TellClientForceReset");

	UObject::ProcessEvent(Func, nullptr);
}

}

