#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_TGF_SwitchWeaponSlot_SwitchNext

#include "Basic.hpp"

#include "GA_TGF_SwitchWeaponSlot_SwitchNext_classes.hpp"
#include "GA_TGF_SwitchWeaponSlot_SwitchNext_parameters.hpp"


namespace SDK
{

// Function GA_TGF_SwitchWeaponSlot_SwitchNext.GA_TGF_SwitchWeaponSlot_SwitchNext_C.GetSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ETgfWeaponChangeSlot                    Slot                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_TGF_SwitchWeaponSlot_SwitchNext_C::GetSlot(ETgfWeaponChangeSlot* Slot) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_TGF_SwitchWeaponSlot_SwitchNext_C", "GetSlot");

	Params::GA_TGF_SwitchWeaponSlot_SwitchNext_C_GetSlot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Slot != nullptr)
		*Slot = Parms.Slot;
}

}

