#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_PlayerAttr_AdditionalElementFire

#include "Basic.hpp"

#include "GE_PlayerAttr_AdditionalElementNone_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_PlayerAttr_AdditionalElementFire.GE_PlayerAttr_AdditionalElementFire_C
// 0x0000 (0x08A8 - 0x08A8)
class UGE_PlayerAttr_AdditionalElementFire_C final : public UGE_PlayerAttr_AdditionalElementNone_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_PlayerAttr_AdditionalElementFire_C">();
	}
	static class UGE_PlayerAttr_AdditionalElementFire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_PlayerAttr_AdditionalElementFire_C>();
	}
};
static_assert(alignof(UGE_PlayerAttr_AdditionalElementFire_C) == 0x000008, "Wrong alignment on UGE_PlayerAttr_AdditionalElementFire_C");
static_assert(sizeof(UGE_PlayerAttr_AdditionalElementFire_C) == 0x0008A8, "Wrong size on UGE_PlayerAttr_AdditionalElementFire_C");

}

