#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_LootBeam

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_LootBeam.I_LootBeam_C
// 0x0000 (0x0028 - 0x0028)
class II_LootBeam_C final : public IInterface
{
public:
	void UpdateMaxQuality();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"I_LootBeam_C">();
	}
	static class II_LootBeam_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<II_LootBeam_C>();
	}
};
static_assert(alignof(II_LootBeam_C) == 0x000008, "Wrong alignment on II_LootBeam_C");
static_assert(sizeof(II_LootBeam_C) == 0x000028, "Wrong size on II_LootBeam_C");

}

