#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LISlua425

#include "Basic.hpp"


namespace SDK
{

// Enum LISlua425.EINTLPropertyClass
// NumValues: 0x001F
enum class EINTLPropertyClass : uint8
{
	Byte                                     = 0,
	Int8                                     = 1,
	Int16                                    = 2,
	Int                                      = 3,
	Int64                                    = 4,
	UInt16                                   = 5,
	UInt32                                   = 6,
	UInt64                                   = 7,
	UnsizedInt                               = 8,
	UnsizedUInt                              = 9,
	Float                                    = 10,
	Double                                   = 11,
	Bool                                     = 12,
	SoftClass                                = 13,
	WeakObject                               = 14,
	LazyObject                               = 15,
	SoftObject                               = 16,
	Class                                    = 17,
	Object                                   = 18,
	Interface                                = 19,
	Name                                     = 20,
	Str                                      = 21,
	Array                                    = 22,
	Map                                      = 23,
	Set                                      = 24,
	Struct                                   = 25,
	Delegate                                 = 26,
	MulticastDelegate                        = 27,
	Text                                     = 28,
	Enum                                     = 29,
	EINTLPropertyClass_MAX                   = 30,
};

// ScriptStruct LISlua425.INTLLuaBPVar
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FINTLLuaBPVar final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FINTLLuaBPVar) == 0x000008, "Wrong alignment on FINTLLuaBPVar");
static_assert(sizeof(FINTLLuaBPVar) == 0x000020, "Wrong size on FINTLLuaBPVar");

}

