#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GuideWindow

#include "Basic.hpp"

#include "WBP_GuideWindow_classes.hpp"
#include "WBP_GuideWindow_parameters.hpp"


namespace SDK
{

// Function WBP_GuideWindow.WBP_GuideWindow_C.BndEvt__WBP_GuideWindow_ButtonClose_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_GuideWindow_C::BndEvt__WBP_GuideWindow_ButtonClose_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "BndEvt__WBP_GuideWindow_ButtonClose_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_GuideWindow_C_BndEvt__WBP_GuideWindow_ButtonClose_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.BndEvt__WBP_GuideWindow_ButtonOut_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_GuideWindow_C::BndEvt__WBP_GuideWindow_ButtonOut_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "BndEvt__WBP_GuideWindow_ButtonOut_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void UWBP_GuideWindow_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.ExecuteUbergraph_WBP_GuideWindow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GuideWindow_C::ExecuteUbergraph_WBP_GuideWindow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "ExecuteUbergraph_WBP_GuideWindow");

	Params::WBP_GuideWindow_C_ExecuteUbergraph_WBP_GuideWindow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.InitConfigData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_GuideWindow_C::InitConfigData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "InitConfigData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.OnItemSelect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Select_Id                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GuideWindow_C::OnItemSelect(class FName Select_Id)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "OnItemSelect");

	Params::WBP_GuideWindow_C_OnItemSelect Parms{};

	Parms.Select_Id = Select_Id;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.OnUserKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_GuideWindow_C::OnUserKeyUp(const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "OnUserKeyUp");

	Params::WBP_GuideWindow_C_OnUserKeyUp Parms{};

	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.ReceiveOnClose
// (Event, Public, BlueprintEvent)

void UWBP_GuideWindow_C::ReceiveOnClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "ReceiveOnClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.ReceiveOnOpen
// (Event, Public, BlueprintEvent)
// Parameters:
// class UTGFWindowArgs*                   Args                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_GuideWindow_C::ReceiveOnOpen(class UTGFWindowArgs* Args)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "ReceiveOnOpen");

	Params::WBP_GuideWindow_C_ReceiveOnOpen Parms{};

	Parms.Args = Args;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.SetDetail
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_GuideWindow_C::SetDetail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "SetDetail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.SetSheetList
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_GuideWindow_C::SetSheetList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "SetSheetList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuideWindow.WBP_GuideWindow_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UWBP_GuideWindow_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuideWindow_C", "GetModuleName");

	Params::WBP_GuideWindow_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

