#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tooltip_GemItem

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Tooltip_GemItem.WBP_Tooltip_GemItem_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct WBP_Tooltip_GemItem_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tooltip_GemItem_C_GetModuleName) == 0x000008, "Wrong alignment on WBP_Tooltip_GemItem_C_GetModuleName");
static_assert(sizeof(WBP_Tooltip_GemItem_C_GetModuleName) == 0x000010, "Wrong size on WBP_Tooltip_GemItem_C_GetModuleName");
static_assert(offsetof(WBP_Tooltip_GemItem_C_GetModuleName, ReturnValue) == 0x000000, "Member 'WBP_Tooltip_GemItem_C_GetModuleName::ReturnValue' has a wrong offset!");

}

