#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TgfGameMenu

#include "Basic.hpp"

#include "WBP_TgfGameMenu_classes.hpp"
#include "WBP_TgfGameMenu_parameters.hpp"


namespace SDK
{

// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BndEvt__WBP_TgfGameMenu_CloseButton_K2Node_ComponentBoundEvent_6_ButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TgfGameMenu_C::BndEvt__WBP_TgfGameMenu_CloseButton_K2Node_ComponentBoundEvent_6_ButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BndEvt__WBP_TgfGameMenu_CloseButton_K2Node_ComponentBoundEvent_6_ButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BndEvt__WBP_TgfGameMenu_GuideButton_K2Node_ComponentBoundEvent_2_ButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TgfGameMenu_C::BndEvt__WBP_TgfGameMenu_GuideButton_K2Node_ComponentBoundEvent_2_ButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BndEvt__WBP_TgfGameMenu_GuideButton_K2Node_ComponentBoundEvent_2_ButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BndEvt__WBP_TgfGameMenu_OptionsButton_K2Node_ComponentBoundEvent_7_ButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TgfGameMenu_C::BndEvt__WBP_TgfGameMenu_OptionsButton_K2Node_ComponentBoundEvent_7_ButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BndEvt__WBP_TgfGameMenu_OptionsButton_K2Node_ComponentBoundEvent_7_ButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BndEvt__WBP_TgfGameMenu_QuickQuickGameButton_K2Node_ComponentBoundEvent_0_ButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TgfGameMenu_C::BndEvt__WBP_TgfGameMenu_QuickQuickGameButton_K2Node_ComponentBoundEvent_0_ButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BndEvt__WBP_TgfGameMenu_QuickQuickGameButton_K2Node_ComponentBoundEvent_0_ButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BndEvt__WBP_TgfGameMenu_QuitGameButton_K2Node_ComponentBoundEvent_5_ButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TgfGameMenu_C::BndEvt__WBP_TgfGameMenu_QuitGameButton_K2Node_ComponentBoundEvent_5_ButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BndEvt__WBP_TgfGameMenu_QuitGameButton_K2Node_ComponentBoundEvent_5_ButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_TgfGameMenu_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_TgfGameMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_TgfGameMenu_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.ExecuteUbergraph_WBP_TgfGameMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TgfGameMenu_C::ExecuteUbergraph_WBP_TgfGameMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "ExecuteUbergraph_WBP_TgfGameMenu");

	Params::WBP_TgfGameMenu_C_ExecuteUbergraph_WBP_TgfGameMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.InitButtons
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TgfGameMenu_C::InitButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "InitButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.On_Mask_MouseButtonDown
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_TgfGameMenu_C::On_Mask_MouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "On_Mask_MouseButtonDown");

	Params::WBP_TgfGameMenu_C_On_Mask_MouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_TgfGameMenu_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "OnKeyDown");

	Params::WBP_TgfGameMenu_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_TgfGameMenu_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "OnKeyUp");

	Params::WBP_TgfGameMenu_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.OnSubWindowClose
// (BlueprintCallable, BlueprintEvent)

void UWBP_TgfGameMenu_C::OnSubWindowClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "OnSubWindowClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TgfGameMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "PreConstruct");

	Params::WBP_TgfGameMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.ReturnFocus
// (BlueprintCallable, BlueprintEvent)

void UWBP_TgfGameMenu_C::ReturnFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "ReturnFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.SendSelfQuitReport
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TgfGameMenu_C::SendSelfQuitReport()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "SendSelfQuitReport");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.SetAppVersion
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TgfGameMenu_C::SetAppVersion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "SetAppVersion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.SetTriggerBySpectate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TgfGameMenu_C::SetTriggerBySpectate(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "SetTriggerBySpectate");

	Params::WBP_TgfGameMenu_C_SetTriggerBySpectate Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.SetVisility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TgfGameMenu_C::SetVisility(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "SetVisility");

	Params::WBP_TgfGameMenu_C_SetVisility Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.UpdateState
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TgfGameMenu_C::UpdateState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "UpdateState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TgfGameMenu.WBP_TgfGameMenu_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_TgfGameMenu_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TgfGameMenu_C", "BP_GetDesiredFocusTarget");

	Params::WBP_TgfGameMenu_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

